services:
  - type: web
    name: smart-attendance-system
    env: docker
    buildCommand: docker build -t smart-attendance .
    startCommand: docker run -p $PORT:8080 smart-attendance
    envVars:
      - key: PORT
        value: 8080 